CREATE OR REPLACE FUNCTION public.func_seed_countries()
  RETURNS void
AS
$BODY$
    BEGIN

        INSERT INTO country(name_nl, code) VALUES ('Afghanistan', 'AF');
        INSERT INTO country(name_nl, code) VALUES ('Åland', 'AX');
        INSERT INTO country(name_nl, code) VALUES ('Albanië', 'AL');
        INSERT INTO country(name_nl, code) VALUES ('Algerije', 'DZ');
        INSERT INTO country(name_nl, code) VALUES ('Amerikaanse Maagdeneilanden', 'VI');
        INSERT INTO country(name_nl, code) VALUES ('Amerikaans-Samoa', 'AS');
        INSERT INTO country(name_nl, code) VALUES ('Andorra', 'AD');
        INSERT INTO country(name_nl, code) VALUES ('Angola', 'AO');
        INSERT INTO country(name_nl, code) VALUES ('Anguilla', 'AI');
        INSERT INTO country(name_nl, code) VALUES ('Antarctica', 'AQ');
        INSERT INTO country(name_nl, code) VALUES ('Antigua en Barbuda', 'AG');
        INSERT INTO country(name_nl, code) VALUES ('Argentinië', 'AR');
        INSERT INTO country(name_nl, code) VALUES ('Armenië', 'AM');
        INSERT INTO country(name_nl, code) VALUES ('Aruba', 'AW');
        INSERT INTO country(name_nl, code) VALUES ('Australië', 'AU');
        INSERT INTO country(name_nl, code) VALUES ('Azerbeidzjan', 'AZ');
        INSERT INTO country(name_nl, code) VALUES ('Bahama''s', 'BS');
        INSERT INTO country(name_nl, code) VALUES ('Bahrein', 'BH');
        INSERT INTO country(name_nl, code) VALUES ('Bangladesh', 'BD');
        INSERT INTO country(name_nl, code) VALUES ('Barbados', 'BB');
        INSERT INTO country(name_nl, code) VALUES ('België', 'BE');
        INSERT INTO country(name_nl, code) VALUES ('Belize', 'BZ');
        INSERT INTO country(name_nl, code) VALUES ('Benin', 'BJ');
        INSERT INTO country(name_nl, code) VALUES ('Bermuda', 'BM');
        INSERT INTO country(name_nl, code) VALUES ('Bhutan', 'BT');
        INSERT INTO country(name_nl, code) VALUES ('Bolivia', 'BO');
        INSERT INTO country(name_nl, code) VALUES ('Caribisch Nederland', 'BQ');
        INSERT INTO country(name_nl, code) VALUES ('Bosnië en Herzegovina', 'BA');
        INSERT INTO country(name_nl, code) VALUES ('Botswana', 'BW');
        INSERT INTO country(name_nl, code) VALUES ('Bouveteiland', 'BV');
        INSERT INTO country(name_nl, code) VALUES ('Brazilië', 'BR');
        INSERT INTO country(name_nl, code) VALUES ('Britse Maagdeneilanden', 'VG');
        INSERT INTO country(name_nl, code) VALUES ('Brits Indische Oceaanterritorium', 'IO');
        INSERT INTO country(name_nl, code) VALUES ('Brunei', 'BN');
        INSERT INTO country(name_nl, code) VALUES ('Bulgarije', 'BG');
        INSERT INTO country(name_nl, code) VALUES ('Burkina Faso', 'BF');
        INSERT INTO country(name_nl, code) VALUES ('Burundi', 'BI');
        INSERT INTO country(name_nl, code) VALUES ('Cambodja', 'KH');
        INSERT INTO country(name_nl, code) VALUES ('Canada', 'CA');
        INSERT INTO country(name_nl, code) VALUES ('Centraal-Afrikaanse Republiek', 'CF');
        INSERT INTO country(name_nl, code) VALUES ('Chili', 'CL');
        INSERT INTO country(name_nl, code) VALUES ('China', 'CN');
        INSERT INTO country(name_nl, code) VALUES ('Christmaseiland', 'CX');
        INSERT INTO country(name_nl, code) VALUES ('Cocoseilanden', 'CC');
        INSERT INTO country(name_nl, code) VALUES ('Colombia', 'CO');
        INSERT INTO country(name_nl, code) VALUES ('Comoren', 'KM');
        INSERT INTO country(name_nl, code) VALUES ('Congo-Brazzaville', 'CG');
        INSERT INTO country(name_nl, code) VALUES ('Congo-Kinshasa', 'CD');
        INSERT INTO country(name_nl, code) VALUES ('Cookeilanden', 'CK');
        INSERT INTO country(name_nl, code) VALUES ('Costa Rica', 'CR');
        INSERT INTO country(name_nl, code) VALUES ('Cuba', 'CU');
        INSERT INTO country(name_nl, code) VALUES ('Curaçao', 'CW');
        INSERT INTO country(name_nl, code) VALUES ('Cyprus', 'CY');
        INSERT INTO country(name_nl, code) VALUES ('Denemarken', 'DK');
        INSERT INTO country(name_nl, code) VALUES ('Djibouti', 'DJ');
        INSERT INTO country(name_nl, code) VALUES ('Dominica', 'DM');
        INSERT INTO country(name_nl, code) VALUES ('Dominicaanse Republiek', 'DO');
        INSERT INTO country(name_nl, code) VALUES ('Duitsland', 'DE');
        INSERT INTO country(name_nl, code) VALUES ('Ecuador', 'EC');
        INSERT INTO country(name_nl, code) VALUES ('Egypte', 'EG');
        INSERT INTO country(name_nl, code) VALUES ('El Salvador', 'SV');
        INSERT INTO country(name_nl, code) VALUES ('Equatoriaal-Guinea', 'GQ');
        INSERT INTO country(name_nl, code) VALUES ('Eritrea', 'ER');
        INSERT INTO country(name_nl, code) VALUES ('Estland', 'EE');
        INSERT INTO country(name_nl, code) VALUES ('Ethiopië', 'ET');
        INSERT INTO country(name_nl, code) VALUES ('Faeröer', 'FO');
        INSERT INTO country(name_nl, code) VALUES ('Falklandeilanden', 'FK');
        INSERT INTO country(name_nl, code) VALUES ('Fiji', 'FJ');
        INSERT INTO country(name_nl, code) VALUES ('Filipijnen', 'PH');
        INSERT INTO country(name_nl, code) VALUES ('Finland', 'FI');
        INSERT INTO country(name_nl, code) VALUES ('Frankrijk', 'FR');
        INSERT INTO country(name_nl, code) VALUES ('Franse Zuidelijke en Antarctische Gebieden', 'TF');
        INSERT INTO country(name_nl, code) VALUES ('Frans-Guyana', 'GF');
        INSERT INTO country(name_nl, code) VALUES ('Frans-Polynesië', 'PF');
        INSERT INTO country(name_nl, code) VALUES ('Gabon', 'GA');
        INSERT INTO country(name_nl, code) VALUES ('Gambia', 'GM');
        INSERT INTO country(name_nl, code) VALUES ('Georgië', 'GE');
        INSERT INTO country(name_nl, code) VALUES ('Ghana', 'GH');
        INSERT INTO country(name_nl, code) VALUES ('Gibraltar', 'GI');
        INSERT INTO country(name_nl, code) VALUES ('Grenada', 'GD');
        INSERT INTO country(name_nl, code) VALUES ('Griekenland', 'GR');
        INSERT INTO country(name_nl, code) VALUES ('Groenland', 'GL');
        INSERT INTO country(name_nl, code) VALUES ('Guadeloupe', 'GP');
        INSERT INTO country(name_nl, code) VALUES ('Guam', 'GU');
        INSERT INTO country(name_nl, code) VALUES ('Guatemala', 'GT');
        INSERT INTO country(name_nl, code) VALUES ('Guernsey', 'GG');
        INSERT INTO country(name_nl, code) VALUES ('Guinee', 'GN');
        INSERT INTO country(name_nl, code) VALUES ('Guinee-Bissau', 'GW');
        INSERT INTO country(name_nl, code) VALUES ('Guyana', 'GY');
        INSERT INTO country(name_nl, code) VALUES ('Haïti', 'HT');
        INSERT INTO country(name_nl, code) VALUES ('Heard en McDonaldeilanden', 'HM');
        INSERT INTO country(name_nl, code) VALUES ('Honduras', 'HN');
        INSERT INTO country(name_nl, code) VALUES ('Hongarije', 'HU');
        INSERT INTO country(name_nl, code) VALUES ('Hongkong', 'HK');
        INSERT INTO country(name_nl, code) VALUES ('Ierland', 'IE');
        INSERT INTO country(name_nl, code) VALUES ('IJsland', 'IS');
        INSERT INTO country(name_nl, code) VALUES ('India', 'IN');
        INSERT INTO country(name_nl, code) VALUES ('Indonesië', 'ID');
        INSERT INTO country(name_nl, code) VALUES ('Irak', 'IQ');
        INSERT INTO country(name_nl, code) VALUES ('Iran', 'IR');
        INSERT INTO country(name_nl, code) VALUES ('Israël', 'IL');
        INSERT INTO country(name_nl, code) VALUES ('Italië', 'IT');
        INSERT INTO country(name_nl, code) VALUES ('Ivoorkust', 'CI');
        INSERT INTO country(name_nl, code) VALUES ('Jamaica', 'JM');
        INSERT INTO country(name_nl, code) VALUES ('Japan', 'JP');
        INSERT INTO country(name_nl, code) VALUES ('Jemen', 'YE');
        INSERT INTO country(name_nl, code) VALUES ('Jersey', 'JE');
        INSERT INTO country(name_nl, code) VALUES ('Jordanië', 'JO');
        INSERT INTO country(name_nl, code) VALUES ('Kaaimaneilanden', 'KY');
        INSERT INTO country(name_nl, code) VALUES ('Kaapverdië', 'CV');
        INSERT INTO country(name_nl, code) VALUES ('Kameroen', 'CM');
        INSERT INTO country(name_nl, code) VALUES ('Kazachstan', 'KZ');
        INSERT INTO country(name_nl, code) VALUES ('Kenia', 'KE');
        INSERT INTO country(name_nl, code) VALUES ('Kirgizië', 'KG');
        INSERT INTO country(name_nl, code) VALUES ('Kiribati', 'KI');
        INSERT INTO country(name_nl, code) VALUES ('Kleine afgelegen eilanden van de Verenigde Staten', 'UM');
        INSERT INTO country(name_nl, code) VALUES ('Koeweit', 'KW');
        INSERT INTO country(name_nl, code) VALUES ('Kroatië', 'HR');
        INSERT INTO country(name_nl, code) VALUES ('Laos', 'LA');
        INSERT INTO country(name_nl, code) VALUES ('Lesotho', 'LS');
        INSERT INTO country(name_nl, code) VALUES ('Letland', 'LV');
        INSERT INTO country(name_nl, code) VALUES ('Libanon', 'LB');
        INSERT INTO country(name_nl, code) VALUES ('Liberia', 'LR');
        INSERT INTO country(name_nl, code) VALUES ('Libië', 'LY');
        INSERT INTO country(name_nl, code) VALUES ('Liechtenstein', 'LI');
        INSERT INTO country(name_nl, code) VALUES ('Litouwen', 'LT');
        INSERT INTO country(name_nl, code) VALUES ('Luxemburg', 'LU');
        INSERT INTO country(name_nl, code) VALUES ('Macau', 'MO');
        INSERT INTO country(name_nl, code) VALUES ('Macedonië', 'MK');
        INSERT INTO country(name_nl, code) VALUES ('Madagaskar', 'MG');
        INSERT INTO country(name_nl, code) VALUES ('Malawi', 'MW');
        INSERT INTO country(name_nl, code) VALUES ('Maldiven', 'MV');
        INSERT INTO country(name_nl, code) VALUES ('Maleisië', 'MY');
        INSERT INTO country(name_nl, code) VALUES ('Mali', 'ML');
        INSERT INTO country(name_nl, code) VALUES ('Malta', 'MT');
        INSERT INTO country(name_nl, code) VALUES ('Man', 'IM');
        INSERT INTO country(name_nl, code) VALUES ('Marokko', 'MA');
        INSERT INTO country(name_nl, code) VALUES ('Marshalleilanden', 'MH');
        INSERT INTO country(name_nl, code) VALUES ('Martinique', 'MQ');
        INSERT INTO country(name_nl, code) VALUES ('Mauritanië', 'MR');
        INSERT INTO country(name_nl, code) VALUES ('Mauritius', 'MU');
        INSERT INTO country(name_nl, code) VALUES ('Mayotte', 'YT');
        INSERT INTO country(name_nl, code) VALUES ('Mexico', 'MX');
        INSERT INTO country(name_nl, code) VALUES ('Micronesia', 'FM');
        INSERT INTO country(name_nl, code) VALUES ('Moldavië', 'MD');
        INSERT INTO country(name_nl, code) VALUES ('Monaco', 'MC');
        INSERT INTO country(name_nl, code) VALUES ('Mongolië', 'MN');
        INSERT INTO country(name_nl, code) VALUES ('Montenegro', 'ME');
        INSERT INTO country(name_nl, code) VALUES ('Montserrat', 'MS');
        INSERT INTO country(name_nl, code) VALUES ('Mozambique', 'MZ');
        INSERT INTO country(name_nl, code) VALUES ('Myanmar', 'MM');
        INSERT INTO country(name_nl, code) VALUES ('Namibië', 'NA');
        INSERT INTO country(name_nl, code) VALUES ('Nauru', 'NR');
        INSERT INTO country(name_nl, code) VALUES ('Nederland', 'NL');
        INSERT INTO country(name_nl, code) VALUES ('Nepal', 'NP');
        INSERT INTO country(name_nl, code) VALUES ('Nicaragua', 'NI');
        INSERT INTO country(name_nl, code) VALUES ('Nieuw-Caledonië', 'NC');
        INSERT INTO country(name_nl, code) VALUES ('Nieuw-Zeeland', 'NZ');
        INSERT INTO country(name_nl, code) VALUES ('Niger', 'NE');
        INSERT INTO country(name_nl, code) VALUES ('Nigeria', 'NG');
        INSERT INTO country(name_nl, code) VALUES ('Niue', 'NU');
        INSERT INTO country(name_nl, code) VALUES ('Noordelijke Marianen', 'MP');
        INSERT INTO country(name_nl, code) VALUES ('Noord-Korea', 'KP');
        INSERT INTO country(name_nl, code) VALUES ('Noorwegen', 'NO');
        INSERT INTO country(name_nl, code) VALUES ('Norfolk', 'NF');
        INSERT INTO country(name_nl, code) VALUES ('Oeganda', 'UG');
        INSERT INTO country(name_nl, code) VALUES ('Oekraïne', 'UA');
        INSERT INTO country(name_nl, code) VALUES ('Oezbekistan', 'UZ');
        INSERT INTO country(name_nl, code) VALUES ('Oman', 'OM');
        INSERT INTO country(name_nl, code) VALUES ('Oostenrijk', 'AT');
        INSERT INTO country(name_nl, code) VALUES ('Oost-Timor', 'TL');
        INSERT INTO country(name_nl, code) VALUES ('Pakistan', 'PK');
        INSERT INTO country(name_nl, code) VALUES ('Palau', 'PW');
        INSERT INTO country(name_nl, code) VALUES ('Palestina', 'PS');
        INSERT INTO country(name_nl, code) VALUES ('Panama', 'PA');
        INSERT INTO country(name_nl, code) VALUES ('Papoea-Nieuw-Guinea', 'PG');
        INSERT INTO country(name_nl, code) VALUES ('Paraguay', 'PY');
        INSERT INTO country(name_nl, code) VALUES ('Peru', 'PE');
        INSERT INTO country(name_nl, code) VALUES ('Pitcairneilanden', 'PN');
        INSERT INTO country(name_nl, code) VALUES ('Polen', 'PL');
        INSERT INTO country(name_nl, code) VALUES ('Portugal', 'PT');
        INSERT INTO country(name_nl, code) VALUES ('Puerto Rico', 'PR');
        INSERT INTO country(name_nl, code) VALUES ('Qatar', 'QA');
        INSERT INTO country(name_nl, code) VALUES ('Réunion', 'RE');
        INSERT INTO country(name_nl, code) VALUES ('Roemenië', 'RO');
        INSERT INTO country(name_nl, code) VALUES ('Rusland', 'RU');
        INSERT INTO country(name_nl, code) VALUES ('Rwanda', 'RW');
        INSERT INTO country(name_nl, code) VALUES ('Saint-Barthélemy', 'BL');
        INSERT INTO country(name_nl, code) VALUES ('Saint Kitts en Nevis', 'KN');
        INSERT INTO country(name_nl, code) VALUES ('Saint Lucia', 'LC');
        INSERT INTO country(name_nl, code) VALUES ('Saint-Pierre en Miquelon', 'PM');
        INSERT INTO country(name_nl, code) VALUES ('Saint Vincent en de Grenadines', 'VC');
        INSERT INTO country(name_nl, code) VALUES ('Salomonseilanden', 'SB');
        INSERT INTO country(name_nl, code) VALUES ('Samoa', 'WS');
        INSERT INTO country(name_nl, code) VALUES ('San Marino', 'SM');
        INSERT INTO country(name_nl, code) VALUES ('Saoedi-Arabië', 'SA');
        INSERT INTO country(name_nl, code) VALUES ('Sao Tomé en Principe', 'ST');
        INSERT INTO country(name_nl, code) VALUES ('Senegal', 'SN');
        INSERT INTO country(name_nl, code) VALUES ('Servië', 'RS');
        INSERT INTO country(name_nl, code) VALUES ('Seychellen', 'SC');
        INSERT INTO country(name_nl, code) VALUES ('Sierra Leone', 'SL');
        INSERT INTO country(name_nl, code) VALUES ('Singapore', 'SG');
        INSERT INTO country(name_nl, code) VALUES ('Sint-Helena, Ascension en Tristan da Cunha', 'SH');
        INSERT INTO country(name_nl, code) VALUES ('Sint-Maarten', 'MF');
        INSERT INTO country(name_nl, code) VALUES ('Sint Maarten', 'SX');
        INSERT INTO country(name_nl, code) VALUES ('Slovenië', 'SI');
        INSERT INTO country(name_nl, code) VALUES ('Slowakije', 'SK');
        INSERT INTO country(name_nl, code) VALUES ('Soedan', 'SD');
        INSERT INTO country(name_nl, code) VALUES ('Somalië', 'SO');
        INSERT INTO country(name_nl, code) VALUES ('Spanje', 'ES');
        INSERT INTO country(name_nl, code) VALUES ('Spitsbergen en Jan Mayen', 'SJ');
        INSERT INTO country(name_nl, code) VALUES ('Sri Lanka', 'LK');
        INSERT INTO country(name_nl, code) VALUES ('Suriname', 'SR');
        INSERT INTO country(name_nl, code) VALUES ('Swaziland', 'SZ');
        INSERT INTO country(name_nl, code) VALUES ('Syrië', 'SY');
        INSERT INTO country(name_nl, code) VALUES ('Tadzjikistan', 'TJ');
        INSERT INTO country(name_nl, code) VALUES ('Taiwan', 'TW');
        INSERT INTO country(name_nl, code) VALUES ('Tanzania', 'TZ');
        INSERT INTO country(name_nl, code) VALUES ('Thailand', 'TH');
        INSERT INTO country(name_nl, code) VALUES ('Togo', 'TG');
        INSERT INTO country(name_nl, code) VALUES ('Tokelau', 'TK');
        INSERT INTO country(name_nl, code) VALUES ('Tonga', 'TO');
        INSERT INTO country(name_nl, code) VALUES ('Trinidad en Tobago', 'TT');
        INSERT INTO country(name_nl, code) VALUES ('Tsjaad', 'TD');
        INSERT INTO country(name_nl, code) VALUES ('Tsjechië', 'CZ');
        INSERT INTO country(name_nl, code) VALUES ('Tunesië', 'TN');
        INSERT INTO country(name_nl, code) VALUES ('Turkije', 'TR');
        INSERT INTO country(name_nl, code) VALUES ('Turkmenistan', 'TM');
        INSERT INTO country(name_nl, code) VALUES ('Turks- en Caicoseilanden', 'TC');
        INSERT INTO country(name_nl, code) VALUES ('Tuvalu', 'TV');
        INSERT INTO country(name_nl, code) VALUES ('Uruguay', 'UY');
        INSERT INTO country(name_nl, code) VALUES ('Vanuatu', 'VU');
        INSERT INTO country(name_nl, code) VALUES ('Vaticaanstad', 'VA');
        INSERT INTO country(name_nl, code) VALUES ('Venezuela', 'VE');
        INSERT INTO country(name_nl, code) VALUES ('Verenigde Arabische Emiraten', 'AE');
        INSERT INTO country(name_nl, code) VALUES ('Verenigde Staten', 'US');
        INSERT INTO country(name_nl, code) VALUES ('Verenigd Koninkrijk', 'GB');
        INSERT INTO country(name_nl, code) VALUES ('Vietnam', 'VN');
        INSERT INTO country(name_nl, code) VALUES ('Wallis en Futuna', 'WF');
        INSERT INTO country(name_nl, code) VALUES ('Westelijke Sahara', 'EH');
        INSERT INTO country(name_nl, code) VALUES ('Wit-Rusland', 'BY');
        INSERT INTO country(name_nl, code) VALUES ('Zambia', 'ZM');
        INSERT INTO country(name_nl, code) VALUES ('Zimbabwe', 'ZW');
        INSERT INTO country(name_nl, code) VALUES ('Zuid-Afrika', 'ZA');
        INSERT INTO country(name_nl, code) VALUES ('Zuid-Georgia en de Zuidelijke Sandwicheilanden', 'GS');
        INSERT INTO country(name_nl, code) VALUES ('Zuid-Korea', 'KR');
        INSERT INTO country(name_nl, code) VALUES ('Zuid-Soedan', 'SS');
        INSERT INTO country(name_nl, code) VALUES ('Zweden', 'SE');
        INSERT INTO country(name_nl, code) VALUES ('Zwitserland', 'CH');

        UPDATE country SET priority = TRUE
        WHERE code IN ('BE', 'NL', 'FR', 'DE', 'LU');

    END;
$BODY$
LANGUAGE plpgsql VOLATILE SECURITY DEFINER;

SELECT func_seed_countries();